version: "3"

services:

  # GWS
  gws:
    build:
      context: ./Dockerfile-local
    # command: ["--runserver", "skeleton"]
    environment:
      - LAB_NAME=skeleton
      - LAB_TOKEN=
      - LAB_URI=
      - START_MODE=
    ports:
      - "3000:3000"
    container_name: gws
      # - VIRTUAL_PORT=3000
      # - VIRTUAL_HOST=lab.(VIRTUAL_HOST)
      # - LETSENCRYPT_HOST=lab.(VIRTUAL_HOST)
      # - LETSENCRYPT_EMAIL=admin@gencovery.com
    volumes:
      - ../lab2:/app/gws/
