image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  GIT_DEPTH: 0
  CPU: cpu
  GPU: gpu
  GLAB: glab
  CODELAB: codelab

stages:
  - build-cpu-glab
  - build-gpu-glab
  - build-cpu-codelab
  - build-gpu-codelab

#  Build the glab cpu images and push them to the registry
build-cpu-glab:
  stage: build-cpu-glab
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Build the gws (GLAB) image with a latest tag and a tag for the commit
    - docker build --build-arg IMAGE="ubuntu:20.04" --cache-from $CI_REGISTRY_IMAGE/$GLAB-$CPU:latest --tag $CI_REGISTRY_IMAGE/$GLAB-$CPU:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE/$GLAB-$CPU:latest . -f dockerfile/$GLAB/Dockerfile
    # Push both image in the registry
    - docker push $CI_REGISTRY_IMAGE/$GLAB-$CPU:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/$GLAB-$CPU:latest
  only:
    - master
  when: manual


#  Build the glab gpu images and push them to the registry
build-gpu-glab:
  stage: build-gpu-glab
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Build the gws (GLAB) image with a latest tag and a tag for the commit
    - docker build --build-arg IMAGE="nvidia/cuda:11.2.1-runtime-ubuntu20.04" --cache-from $CI_REGISTRY_IMAGE/$GLAB-$GPU:latest --tag $CI_REGISTRY_IMAGE/$GLAB-$GPU:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE/$GLAB-$GPU:latest . -f dockerfile/$GLAB/Dockerfile
    # Push both image in the registry
    - docker push $CI_REGISTRY_IMAGE/$GLAB-$GPU:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/$GLAB-$GPU:latest
  only:
    - master
  when: manual

#  Build the codelab cpu images and push them to the registry
build-cpu-codelab:
  stage: build-cpu-codelab
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Build the code server (CODELAB) image from the GLAB Image with a latest tag and a tag for the commit
    - docker build --build-arg IMAGE="$CI_REGISTRY_IMAGE/$GLAB-$CPU:latest" --cache-from $CI_REGISTRY_IMAGE/$CODELAB-$CPU:latest --tag $CI_REGISTRY_IMAGE/$CODELAB-$CPU:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE/$CODELAB-$CPU:latest . -f dockerfile/$CODELAB/Dockerfile
    # Push both image in the registry
    - docker push $CI_REGISTRY_IMAGE/$CODELAB-$CPU:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/$CODELAB-$CPU:latest

  only:
    - master
  when: manual

#  Build the codelab gpu images and push them to the registry
build-gpu-codelab:
  stage: build-gpu-codelab
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Build the code server (CODELAB) image from the GLAB Image with a latest tag and a tag for the commit
    - docker build --build-arg IMAGE="$CI_REGISTRY_IMAGE/$GLAB-$GPU:latest" --cache-from $CI_REGISTRY_IMAGE/$CODELAB-$GPU:latest --tag $CI_REGISTRY_IMAGE/$CODELAB-$GPU:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE/$CODELAB-$GPU:latest . -f dockerfile/$CODELAB/Dockerfile
    # Push both image in the registry
    - docker push $CI_REGISTRY_IMAGE/$CODELAB-$GPU:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/$CODELAB-$GPU:latest

  only:
    - master
  when: manual
