version: "3"

services:

  # Jupiter lab
  jlab:
    image: jlab:latest
    build:
      context: ./docker-jlab
    command: ["--runserver"]
    environment:
      - VIRTUAL_PORT=8888
      - VIRTUAL_HOST=jlab.(VIRTUAL_HOST)
      - LETSENCRYPT_HOST=jlab.(VIRTUAL_HOST)
      - LETSENCRYPT_EMAIL=admin@gencovery.com
      - JLAB_TOKEN=(JLAB_TOKEN)
      - JLAB_HOME_DIR=(JLAB_HOME_DIR)
    volumes:
      - (APP_DIR):/app/gws/
    networks:
       - gpm_nginx-proxy
    restart: always

networks:
  gpm_nginx-proxy:
    external: true
