version: "3"

services:
  gws:
    image: gws:latest
    build:
      context: ../
    command: ["--runserver", "(LAB_NAME)"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gws.rule=Host(`astro.lab.gencovery.com`)"
      - "traefik.http.routers.gws.entrypoints=websecure"
      - "traefik.http.routers.gws.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.gws.service=gws-service"
      - "traefik.http.services.gws-service.loadbalancer.server.port=3000"

      - "traefik.http.routers.jlab.rule=Host(`astro.lab.gencovery.com`)"
      - "traefik.http.routers.jlab.entrypoints=websecure"
      - "traefik.http.routers.jlab.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.jlab.service=jlab-service"
      - "traefik.http.services.jlab-service.loadbalancer.server.port=8888"

    environment:
      - LAB_NAME:(LAB_NAME)
      - START_MODE:(START_MODE)
      - URI:(URI)
      - TOKEN:(TOKEN)
    volumes:
      - (APP_DIR):/app/gws/
    restart: always
  
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=admin@gencovery.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - gws