version: "3"

services:

  gws:
    build:
      context: ../
      args:
        LAB_NAME: main

    image: gws:latest
    ports:
      - 3000:80
    #volumes:
    #  - /home/ubuntu/work:/app/gws/user
    restart: always
