version: "3"

services:

  gws:
    build:
      context: ../
      args:
        APPDIR: /app/gws
        USERDIR: /home/ubuntu/work
        LABNAME: mylab

    image: gws:latest
    ports:
      - 3000:80
    volumes:
      - /home/ubuntu/work:/app/gws/user
    restart: always
