version: "3"
services:
  gws:
    #build: .
    image: gws:latest
    ports:
      - 3000:80
    # environment:
    #    - VIRTUAL_HOST=XXX.gencovery.com
    #    - LETSENCRYPT_HOST=XXX.gencovery.com
    #    - LETSENCRYPT_EMAIL=admin@gencovery.com
    volumes:
      - /app:/home/ubuntu/work
    # networks:
    #    - nginxproxy_nginx-proxy
    restart: always

# networks:
#   nginxproxy_nginx-proxy:
#     external: true